const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1A1A1A",
    background: "#FAF7F2",
    surface: "#FFFFFF",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1A1A1A",
    primaryForeground: "#FAF7F2",
    secondary: "#F0EBE0",
    secondaryForeground: "#1A1A1A",
    muted: "#F0EBE0",
    mutedForeground: "#6B6B6B",
    accent: "#F0EBE0",
    accentForeground: "#1A1A1A",
    destructive: "#C1331F",
    destructiveForeground: "#FFFFFF",
    border: "#E8E2D8",
    input: "#E8E2D8",
    success: "#2D7D46",
    successForeground: "#FFFFFF",
    warning: "#B45309",
    warningForeground: "#FFFFFF",
    info: "#1D4ED8",
    infoForeground: "#FFFFFF",
  },
  dark: {
    text: "#E8E8E8",
    tint: "#FAF7F2",
    background: "#191919",
    surface: "#252525",
    foreground: "#E8E8E8",
    card: "#252525",
    cardForeground: "#E8E8E8",
    primary: "#FAF7F2",
    primaryForeground: "#1A1A1A",
    secondary: "#2F2F2F",
    secondaryForeground: "#E8E8E8",
    muted: "#2F2F2F",
    mutedForeground: "#9B9B9B",
    accent: "#2F2F2F",
    accentForeground: "#E8E8E8",
    destructive: "#E55039",
    destructiveForeground: "#FFFFFF",
    border: "#2F2F2F",
    input: "#2F2F2F",
    success: "#34A85A",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
  },
  radius: 14,
};

export default colors;
